---
.travis.yml:
  secure: "BKBqztew6bC36ouvEOk7sFTnQYuTA4VLHwF1Wg12ta3uAMscX8ZuVKGWZ9x8BrDuYArWvfW5ymQUKpqMpzJ0Bnr3UcdJY1dtFJYzbKNVuIAPQSfSv3Voe8xSmoRvMyayWu04E0BfJAx7Re0f3rAJcmqhVczWbCZvIxFWbhJ4ggU="
